
daily = read.csv("dailykos.csv")
#dailyMatrix = as.matrix(daily)
#dailyVector = as.vector(dailyMatrix)
kosDist = dist(daily[2:1546], method = "euclidean")
kosHierClust = hclust(kosDist, method = "ward")
kosClusters = cutree(kosHierClust, k=7)
Clust1 = subset(daily, kosClusters==1)
Clust2 = subset(daily, kosClusters==2)
Clust3 = subset(daily, kosClusters==3)
Clust4 = subset(daily, kosClusters==4)
Clust5 = subset(daily, kosClusters==5)
Clust6 = subset(daily, kosClusters==6)
Clust7 = subset(daily, kosClusters==7)
# Alternately HierCluster = split(daily,kosClusters)
HierCluster = split(daily,kosClusters)
table(kosClusters)
tail(sort(colMeans(Clust1[-1])))

#KMeans Clustering
daily = read.csv("dailykos.csv")
set.seed(1000)
KmeansCluster = kmeans(daily[2:1546], centers=7)
KmeansCluster1 = subset(daily, KmeansCluster$cluster == 1)
KmeansCluster2 = subset(daily, KmeansCluster$cluster == 2)
KmeansCluster3 = subset(daily, KmeansCluster$cluster == 3)
KmeansCluster4 = subset(daily, KmeansCluster$cluster == 4)
KmeansCluster5 = subset(daily, KmeansCluster$cluster == 5)
KmeansCluster6 = subset(daily, KmeansCluster$cluster == 6)
KmeansCluster7 = subset(daily, KmeansCluster$cluster == 7)
table(KmeansCluster$cluster)
#could split daily into the clusters by typing:
#KmeansCluster = split(dailykos, KmeansCluster$cluster)
#Then cluster 1 can be accessed by typing KmeansCluster[[1]]
tail(sort(colMeans(KmeansCluster1[-1])))
tail(sort(colMeans(KmeansCluster2[-1])))
tail(sort(colMeans(KmeansCluster3[-1])))
tail(sort(colMeans(KmeansCluster4[-1])))
tail(sort(colMeans(KmeansCluster5[-1])))
tail(sort(colMeans(KmeansCluster6[-1])))
tail(sort(colMeans(KmeansCluster7[-1])))
table(KmeansCluster$cluster,kosClusters)

# 2
airlines = read.csv("AirlinesCluster.csv")
str(airlines)
summary(airlines)
#normalize the data so that all the variables are scaled
library(caret)
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
summary(airlinesNorm)
distances = dist(airlinesNorm, method = "euclidean")
clusterair = hclust(distances, method = "ward")
clusterGroups = cutree(clusterair, k=5)
table(clusterGroups)
tapply(airlines$Balance, clusterGroups, mean)
tapply(airlines$QualMiles, clusterGroups, mean)
tapply(airlines$BonusMiles, clusterGroups, mean)
tapply(airlines$BonusTrans, clusterGroups, mean)
tapply(airlines$FlightMiles, clusterGroups, mean)
tapply(airlines$FlightTrans, clusterGroups, mean)
tapply(airlines$DaysSinceEnroll, clusterGroups, mean)
#Alternately
#colMeans(subset(airlines, clusterGroups == 1))
#colMeans(subset(airlines, clusterGroups == 2))
#colMeans(subset(airlines, clusterGroups == 3))
#colMeans(subset(airlines, clusterGroups == 4))
#colMeans(subset(airlines, clusterGroups == 5))
#OR in a single line
#lapply(split(airlines, clusterGroups), colMeans)

# 3
claims = read.csv("reimbursement.csv")
str(claims)
#table(claims$alzheimers == 1 | claims$arthritis == 1 | claims$cancer == 1 | claims$copd == 1 | claims$depression == 1 | claims$diabetes == 1 | claims$heart.failure == 1 | claims$ihd == 1 | claims$kidney == 1 | claims$osteoporosis == 1 | claims$stroke == 1)
#has.condition = subset(claims, alzheimers == 1 | arthritis == 1 | cancer == 1 | copd == 1 | depression == 1 | diabetes == 1 | heart.failure == 1 | ihd == 1 | kidney == 1 | osteoporosis == 1 | stroke == 1)
#nrow(has.condition)
disease = (claims$alzheimers | claims$arthritis | claims$cancer | claims$copd |claims$depression| claims$diabetes |claims$heart.failure | claims$kidney | claims$ihd |claims$osteoporosis |claims$stroke)
sum(disease)/nrow(claims)
hist(claims$reimbursement2009)
claims$reimbursement2008 = log(claims$reimbursement2008+1)
claims$reimbursement2009 = log(claims$reimbursement2009+1)
set.seed(144)
spl = sample(1:nrow(claims), size=0.7*nrow(claims))
train = claims[spl,]
test = claims[-spl,]
lm.claims = lm(reimbursement2009~., data=train)
summary(lm.claims)
lm.claimstest = predict(lm.claims, newdata=test)
SSE.test = sum((lm.claimstest - test$reimbursement)^2)
RMSE.test = sqrt(SSE/nrow(test))
# OR in a single line code rmse.lm = sqrt(mean((pred.test - test$reimbursement2009)^2))
RMSE.test
#testing set RMSE of the naive baseline model
baseline.pred = mean(train$reimbursement2009)
sqrt(mean((baseline.pred - test$reimbursement2009)^2))

sqrt(mean((test$reimbursement2008-test$reimbursement2009)^2))
train.limited = train
train.limited$reimbursement2009 = NULL
test.limited = test
test.limited$reimbursement2009 = NULL
library(caret)
preproc = preProcess(train.limited)
train.norm = predict(preproc, train.limited)
test.norm = predict(preproc, test.limited)
km = kmeans(train.norm, centers=3)
str(km)
lapply(split(train.norm, km$cluster),colMeans) #or km$centers

#clustering medical beneficiaries
library(flexclust)
km.kcca = as.kcca(km, train.norm)
cluster.train = predict(km.kcca)
cluster.test = predict(km.kcca, newdata=test.norm)
table(cluster.test)
table(cluster.train)
train1 = subset(train, cluster.train==1)
train2 = subset(train, cluster.train==2)
train3 = subset(test, cluster.train==3)
test1 = subset(test, cluster.test==1)
test2 = subset(test, cluster.test==2)
test3 = subset(test, cluster.test==3)
mean(train1$reimbursement2009)
lm2 = lm(reimbursement2009~., data=train2)
lm3 = lm(reimbursement2009~., data=train3)
summary(lm1)
pred.test1 = predict(lm1, newdata=test1)
pred.test2 = predict(lm2, newdata=test2)
pred.test3 = predict(lm3, newdata=test3)
all.predictions = c(pred.test1, pred.test2, pred.test3)
all.outcomes = c(test1$reimbursement2009, test2$reimbursement2009, test3$reimbursement2009)
all.predictions = c(pred.test1, pred.test2, pred.test3)
all.outcomes = c(test1$reimbursement2009, test2$reimbursement2009, test3$reimbursement2009)
sqrt(mean((all.predictions - all.outcomes)^2))